### ISSUE TITLE
Strong arrays comparision

### ISSUE THREAD

**Issue by jackblackjack** [jgillick/jest-array-equal#1]
Can you add strong equalize for
Not pass: expect([1, 2, 4]).toEqualArray([2, 4, 1]); (pass is now)
But pass when: expect([1, 2, 4]).toEqualArray([1, 2, 4]) only.

**Comment by jgillick** [comment]
That's by design. If you want to write a PR that adds an additional strong array comparison to the lib, I'll happily merge it.
